site:
  title: JReleaser
  url: https://jreleaser.org
  start_page: guide::index.adoc
  keys:
    google_analytics: 'G-Q7MK38WE53'

content:
  sources:
    - url: https://github.com/jreleaser/jreleaser.github.io.git
      branches: main
      start_path: docs
    - url: https://github.com/jreleaser/jreleaser.github.io.git
      branches: development
      start_path: docs

ui:
  bundle:
    url: ui-bundle.zip
  supplemental_files: './supplemental_ui'

asciidoc:
  extensions:
    - ./extensions/tabs-block/extension
