name: Push

on:
  push:
    branches: [ main, development ]

jobs:
  push:
    name: push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21.7.3

      - name: Run Antora
        run: npx antora antora-playbook.yml

      - name: Copy landing page
        run: |
          mkdir -p $GITHUB_WORKSPACE/website/releases/latest/download
          cp -rf $GITHUB_WORKSPACE/build/site/* $GITHUB_WORKSPACE/website
          cp -rf $GITHUB_WORKSPACE/landing/* $GITHUB_WORKSPACE/website
          cp -rf $GITHUB_WORKSPACE/VERSION $GITHUB_WORKSPACE/website/releases/latest/download
          cp -rf $GITHUB_WORKSPACE/schema $GITHUB_WORKSPACE/website/schema
          touch $GITHUB_WORKSPACE/website/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          folder: website
          branch: 'gh-pages'
          commit-message: "[CI] Publish Documentation for ${{ github.sha }}"
